### ISSUE TITLE
Spawning a Custom NPC crashes my game.

### ISSUE THREAD

**Issue by anarche0** [KAMKEEL/CustomNPC-Plus#83] opened 2023-05-10 03:49 UTC
**When ever I try to spawn an NPC, the game crashes.**

**[crash-2023-05-09_23.41.52-server.txt](https://github.com/KAMKEEL/CustomNPC-Plus/files/11437838/crash-2023-05-09_23.41.52-server.txt)**

**Versions:*1.8*
* Minecraft: 1.7.10
* Forge: 10.13.4.1614-1.7.10
* CustomNPC+: 

**Can it be reproduced with *just* CustomNPC+? If not, list the other mods *required* to reproduce the issue.**

**Comment by KAMKEEL** [comment] 2023-05-10 23:23
I can't seem to recreate this. Can you try it on `1.8.1` with only CustomNPC+? Make a duplicate of your world when testing.

**Comment by KAMKEEL** [comment] 2023-05-13 19:56
Issue created by `Flan's Mod NPC Vehicles`. It's not by us. We'll sort it out with them

**Closed by KAMKEEL** 2023-05-13 19:56 UTC
