### ISSUE TITLE
Projectile Trails not working

### ISSUE THREAD

**Issue by SonYoureAdopted** [KAMKEEL/CustomNPC-Plus#3] opened 2021-05-18 01:10 UTC
**Issue description:**
When setting a trail for a projectile (like redstone or smoke) it doesn't show the particles
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.7.10
* Forge: 
* CustomNPC+: 

**Can it be reproduced with *just* CustomNPC+? If not, list the other mods *required* to reproduce the issue.**

**Comment by KAMKEEL** [comment] 2021-06-13 20:31
Hello @SonYoureAdopted ,

After recent testing, I am not able to reproduce this issue. All projectile trails seem to be operating on the latest version of 1.1 CustomNPC+. This means it has to either be a mod interacting on your end or some visual setting that you must have enabled. If you are able to explain to me how to recreate this issue let me know. As for now, I am closing this issue.

**Closed by KAMKEEL** 2021-06-13 20:31 UTC
